// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuteReborn.Database;

#nullable disable

namespace MuteReborn.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230913025526_AddBetGuildConfigs")]
    partial class AddBetGuildConfigs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("MuteReborn.Database.Models.BetGuildConfigs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("BetRecordChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HSRBetStartMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BetGuildConfigs");
                });

            modelBuilder.Entity("MuteReborn.Database.Models.MuteRebornGuildConfigs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyMuteRebornTicketCost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("EachTicketDecreaseMuteTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EachTicketIncreaseMuteTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableMuteReborn")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxIncreaseMuteTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MuteRebornGuildConfigs");
                });

            modelBuilder.Entity("MuteReborn.Database.Models.MuteRebornTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebornTicketNum")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MuteRebornTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
